[package]
edition = "2021"
name = "posts_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "posts_integrity"

[dependencies]
serde = "1"
derive_more = "0"

holochain_deterministic_integrity = "0.0.12"
